<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>Assets\LANtern.ico</ApplicationIcon>
    <AssemblyName>LANtern</AssemblyName>
    <AssemblyTitle>LANtern</AssemblyTitle>
    <Product>LANtern</Product>
    <Description>Your screen, anywhere on your LAN.</Description>
    <Version>0.1.2-alpha</Version>
    <FileVersion>0.1.2.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\LANtern.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
